CREATE DATABASE QUANLYTRANGSUC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE QUANLYTRANGSUC;

CREATE TABLE TAIKHOAN (
   ID                   INT AUTO_INCREMENT PRIMARY KEY,
   EMAIL                VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
   PASSWORD             VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
   ROLE                 TINYINT NOT NULL, -- 0: Khách hàng, 1: Admin, 2: Superadmin, 3: .....
   TINHTRANG            TINYINT NOT NULL DEFAULT 1,
   DELETED_AT           DATETIME NULL  -- Không xóa hoàn toàn, chỉ ẩn đi
);

CREATE TABLE ADMIN (
   ID                   INT PRIMARY KEY, -- Liên kết với ID từ bảng TAIKHOAN
   ID_CHINHANH          VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL, -- Chi nhánh mà admin quản lý
   TENADMIN             VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
   SDT                  VARCHAR(15) NULL,
   DIACHI               VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL
);

CREATE TABLE KHACHHANG (
   ID                   INT PRIMARY KEY, -- Liên kết với ID từ bảng TAIKHOAN
   TENKH                VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
   SDT                  VARCHAR(15) NULL,
   DIACHI               VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
   LOAI                 TINYINT NULL,
   GIOITINH             TINYINT NULL -- 1: Nam, 2: Nữ
);

CREATE TABLE CHINHANH (
   ID                   VARCHAR(10) PRIMARY KEY,
   TENCN                VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
   DIACHI               VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
   DELETED_AT           DATETIME NULL  -- Không xóa hoàn toàn, chỉ ẩn đi
);

CREATE TABLE TRANGSUC (
   ID                   INT AUTO_INCREMENT PRIMARY KEY,
   MADM                 VARCHAR(10) NOT NULL,
   TENTS                VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
   GIANIEMYET           BIGINT NOT NULL,
   SLTK                 INT NOT NULL DEFAULT 0,
   MOTA                 TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
   IMAGEURL             LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
   DELETED_AT           DATETIME NULL  -- Không xóa hoàn toàn, chỉ ẩn đi
);

CREATE TABLE DANHMUCTS (
   MADM                 VARCHAR(10) NOT NULL PRIMARY KEY,
   TENDM                VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
);

CREATE TABLE HOADON (
   ID_HOADON            INT AUTO_INCREMENT PRIMARY KEY,
   ID_KHACHHANG         INT NOT NULL,
   NGAYLAPHD            DATE NOT NULL,
   TRIGIAHD             BIGINT NOT NULL,
   TIENPHAITRA          BIGINT NOT NULL,
   TRANGTHAI            TINYINT NOT NULL, -- 0: Chờ xử lý, 1: Đã xử lý, 2: Hủy
   DELETED_AT           DATETIME NULL  -- Không xóa hoàn toàn, chỉ ẩn đi
);

CREATE TABLE GIOHANG (
   ID_GIOHANG           INT AUTO_INCREMENT PRIMARY KEY,
   ID_KHACHHANG         INT NOT NULL
);

CREATE TABLE CHITIETGH (
   ID_TRANGSUC          INT NOT NULL,
   ID_GIOHANG           INT NOT NULL,
   SOLUONG              INT NOT NULL DEFAULT 1,
   PRIMARY KEY (ID_TRANGSUC, ID_GIOHANG)
);

CREATE TABLE CHITIETHD (
   ID_TRANGSUC          INT NOT NULL,
   ID_HOADON            INT NOT NULL,
   SOLUONG              INT NOT NULL DEFAULT 1,
   GIASP                BIGINT NOT NULL,
   PRIMARY KEY (ID_TRANGSUC, ID_HOADON)
);

CREATE TABLE KHUYENMAI (
   ID                   INT AUTO_INCREMENT PRIMARY KEY,
   MAKM                 VARCHAR(100) NOT NULL,
   TENKM                VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
   NGAYBD               DATE NOT NULL,
   NGAYKT               DATE NOT NULL,
   PHANTRAM             FLOAT NOT NULL DEFAULT 0
);

CREATE TABLE CHITIETKM (
   ID_KHUYENMAI         INT NOT NULL,
   ID_TRANGSUC          INT NOT NULL,
   PRIMARY KEY (ID_KHUYENMAI, ID_TRANGSUC)
);

CREATE TABLE TS_CHINHANH (
   ID_TRANGSUC          INT NOT NULL,
   ID_CHINHANH          VARCHAR(10) NOT NULL,
   SLTONKHO             INT NOT NULL DEFAULT 0,
   PRIMARY KEY (ID_TRANGSUC, ID_CHINHANH)
);

ALTER TABLE ADMIN ADD CONSTRAINT FK_ADMIN_TAIKHOAN FOREIGN KEY (ID) REFERENCES TAIKHOAN(ID) ON DELETE RESTRICT;
ALTER TABLE ADMIN ADD CONSTRAINT FK_ADMIN_CHINHANH FOREIGN KEY (ID_CHINHANH) REFERENCES CHINHANH(ID) ON DELETE RESTRICT;

ALTER TABLE KHACHHANG ADD CONSTRAINT FK_KHACHHANG_TAIKHOAN FOREIGN KEY (ID) REFERENCES TAIKHOAN(ID) ON DELETE RESTRICT;

ALTER TABLE TRANGSUC ADD CONSTRAINT FK_TRANGSUC_DANHMUC FOREIGN KEY (MADM) REFERENCES DANHMUCTS(MADM) ON DELETE RESTRICT;

ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (ID_KHACHHANG) REFERENCES KHACHHANG(ID) ON DELETE RESTRICT;

ALTER TABLE GIOHANG ADD CONSTRAINT FK_GIOHANG_KHACHHANG FOREIGN KEY (ID_KHACHHANG) REFERENCES KHACHHANG(ID) ON DELETE RESTRICT;

ALTER TABLE CHITIETGH ADD CONSTRAINT FK_CHITIETGH_TRANGSUC FOREIGN KEY (ID_TRANGSUC) REFERENCES TRANGSUC(ID) ON DELETE RESTRICT;
ALTER TABLE CHITIETGH ADD CONSTRAINT FK_CHITIETGH_GIOHANG FOREIGN KEY (ID_GIOHANG) REFERENCES GIOHANG(ID_GIOHANG) ON DELETE RESTRICT;

ALTER TABLE CHITIETHD ADD CONSTRAINT FK_CHITIETHD_TRANGSUC FOREIGN KEY (ID_TRANGSUC) REFERENCES TRANGSUC(ID) ON DELETE RESTRICT;
ALTER TABLE CHITIETHD ADD CONSTRAINT FK_CHITIETHD_HOADON FOREIGN KEY (ID_HOADON) REFERENCES HOADON(ID_HOADON) ON DELETE RESTRICT;

ALTER TABLE CHITIETKM ADD CONSTRAINT FK_CHITIETKM_KHUYENMAI FOREIGN KEY (ID_KHUYENMAI) REFERENCES KHUYENMAI(ID) ON DELETE RESTRICT;
ALTER TABLE CHITIETKM ADD CONSTRAINT FK_CHITIETKM_TRANGSUC FOREIGN KEY (ID_TRANGSUC) REFERENCES TRANGSUC(ID) ON DELETE RESTRICT;

ALTER TABLE TS_CHINHANH ADD CONSTRAINT FK_TSCHINHANH_TRANGSUC FOREIGN KEY (ID_TRANGSUC) REFERENCES TRANGSUC(ID) ON DELETE RESTRICT;
ALTER TABLE TS_CHINHANH ADD CONSTRAINT FK_TSCHINHANH_CHINHANH FOREIGN KEY (ID_CHINHANH) REFERENCES CHINHANH(ID) ON DELETE RESTRICT;

-- Thêm dữ liệu

-- Tài khoản test

-- test@gmail.com
-- abcdef
INSERT INTO TAIKHOAN (EMAIL, PASSWORD, ROLE, TINHTRANG) 
VALUES ('test@gmail.com', '$2y$10$Sh.HPSQycPtzt7vtFWOTFuPVXU/Qwy0rBTkzEFejymFdKPrfkMisC', 0, 1);

SET @test_id = LAST_INSERT_ID();
INSERT INTO KHACHHANG (ID, TENKH, SDT, DIACHI, LOAI, GIOITINH) 
VALUES (@test_id, 'Nguyễn Văn A', '0123456789', '404 Đường F, HCM', 1, 2);

-- superadmin@gmail.com
-- 123456
INSERT INTO TAIKHOAN (EMAIL, PASSWORD, ROLE, TINHTRANG) 
VALUES ('superadmin@gmail.com', '$2y$10$DPKNeF3xz/clbIKX.uTML./3pdsWJxl1l/abqpp0OnUknnHL5Wwiu', 1, 1);

SET @admin_id = LAST_INSERT_ID();
INSERT INTO ADMIN (ID, ID_CHINHANH, TENADMIN, SDT, DIACHI) 
VALUES (@admin_id, NULL, 'Trần Tiến P', '0123456780', '505 Đường G, HCM');

-- Thêm danh mục
INSERT INTO DANHMUCTS (MADM, TENDM) VALUES
('NKC0', 'Nhẫn')

-- Thêm trang sức
INSERT INTO TRANGSUC (MADM, TENTS, GIANIEMYET, SLTK, MOTA, IMAGEURL, DELETED_AT) VALUES 
('NKC0', 'Nhẫn kim cương phake siêu cấp vip pro', 5000000, 10, 'Nhẫn kim cương siu cấp, dược tạo từ công xường gia công hàng phake lớn nhất thế giưới aka Tung của bingchiling', '\storage\images\1.png', NULL)